language: node_js

node_js:
  - "lts/*"

cache:
  directories:
    - "node_modules"

before_deploy:
  - npm run build

deploy:
  skip_cleanup: true
  provider: npm
  email: "amandio.magalhaes@gmail.com"
  api_key: "a8db55ad-1a42-487c-857b-496365b76432"
  on:
    branch: master
